import { THEME, THEME_PROPS } from "../admin";

export const BASE_THEME = {
  name: THEME.BASE_THEME,
  isActive: true,

  // general
  [THEME_PROPS.LINE_COLOR]: "#a4874f",
  [THEME_PROPS.BD_COLOR]: "#f8f8f8",
  [THEME_PROPS.TITLE_COLOR]: "#2e6177",
  [THEME_PROPS.COLOR]: "#2e6177",
  [THEME_PROPS.LINK_COLOR]: "#a4874f",
  [THEME_PROPS.LINK_HOVER_COLOR]: "#f1d8a8",

  // item
  [THEME_PROPS.BD_COLOR_ITEM]: "#24445C",
  [THEME_PROPS.COLOR_ITEM]: "#c4a368",
  [THEME_PROPS.LINK_ITEM_COLOR]: "#c4a368",
  [THEME_PROPS.LINK_HOVER_ITEM_COLOR]: "#c4a368",

  /*
   menu 1
   */
  // general
  [THEME_PROPS.MENU_1_COLOR]: "#e7e7e7",
  [THEME_PROPS.MENU_1_LINK_COLOR]: "#2e6177",
  [THEME_PROPS.MENU_1_LINK_HOVER_COLOR]: "#a4874f",

  // home
  [THEME_PROPS.MENU_1_HOME_COLOR]: "#e7e7e7",
  [THEME_PROPS.MENU_1_LINK_HOME_COLOR]: "#2e6177",
  [THEME_PROPS.MENU_1_LINK_HOVER_HOME_COLOR]: "#a4874f",

  // item
  [THEME_PROPS.MENU_1_ITEM_COLOR]: "#0f1f26",
  [THEME_PROPS.MENU_1_LINK_ITEM_COLOR]: "#66c3d3",
  [THEME_PROPS.MENU_1_LINK_HOVER_ITEM_COLOR]: "#b5d1d5",

  /*
   menu 2
   */
  // general
  [THEME_PROPS.MENU_2_COLOR]: "#f8f8f8",
  [THEME_PROPS.MENU_2_LINK_COLOR]: "#a4874f",
  [THEME_PROPS.MENU_2_LINK_HOVER_COLOR]: "#e0bf84",

  // home
  [THEME_PROPS.MENU_2_HOME_COLOR]: "#f8f8f8",
  [THEME_PROPS.MENU_2_LINK_HOME_COLOR]: "#a4874f",
  [THEME_PROPS.MENU_2_LINK_HOVER_HOME_COLOR]: "#e0bf84",

  // item
  [THEME_PROPS.MENU_2_ITEM_COLOR]: "#13262f",
  [THEME_PROPS.MENU_2_LINK_ITEM_COLOR]: "#c4a368",
  [THEME_PROPS.MENU_2_LINK_HOVER_ITEM_COLOR]: "#f1d8a8",
};

export const BASE_PRESET_COLOR = {
  name: "Prussian blue",
  color: "#24445C",
};
